import streamlit as st

# =========================
# PAGE HEADER
# =========================

st.markdown("""
<div style="
padding:20px;
border-radius:15px;
background:linear-gradient(135deg,#0f172a,#1e293b);
text-align:center;
margin-bottom:20px;
">
<h1 style="color:white;">💊 Treatment Recommendation System</h1>
<p style="color:#cbd5e1;">
AI Powered Personalized Healthcare Guidance
</p>
</div>
""", unsafe_allow_html=True)

# =========================
# KPI CARDS
# =========================

c1, c2, c3, c4 = st.columns(4)

with c1:
    st.metric("Accuracy", "97%")

with c2:
    st.metric("AI Models", "3")

with c3:
    st.metric("Predictions", "24/7")

with c4:
    st.metric("Patients", "5000+")

st.markdown("---")

# =========================
# INPUT SECTION
# =========================

st.subheader("🩺 Generate Treatment Plan")

col1, col2 = st.columns(2)

with col1:
    disease = st.selectbox(
        "Select Disease",
        [
            "Diabetes",
            "Heart Disease",
            "Kidney Disease"
        ]
    )

with col2:
    severity = st.selectbox(
        "Severity Level",
        [
            "Low",
            "Moderate",
            "High"
        ]
    )

# =========================
# GENERATE PLAN
# =========================

if st.button(
    "🚀 Generate AI Treatment Plan",
    use_container_width=True
):

    st.success("✅ AI Treatment Plan Generated")

    # =====================
    # DISEASE CARD
    # =====================

    st.info(f"""
### 🩺 Disease Selected

**Disease:** {disease}

**Severity:** {severity}
""")

    # =====================
    # DIABETES
    # =====================

    if disease == "Diabetes":

        st.success("""
### 💊 Treatment Recommendations

• Monitor Blood Sugar Daily

• HbA1c Test Every 3 Months

• Take Prescribed Medication

• Follow Diabetic Diet

• Maintain Healthy Weight

• Exercise Regularly
""")

        st.info("""
### 🥗 Diet Plan

• Whole Grains

• Green Vegetables

• Lean Protein

• Nuts and Seeds

• Avoid Sugary Drinks

• Avoid Excess Carbohydrates
""")

        st.warning("""
### ⚠ Precautions

• Never Skip Medication

• Monitor Blood Sugar

• Avoid Junk Food

• Schedule Regular Checkups
""")

        st.success("""
### 🏃 Exercise Plan

• Walking – 30 Minutes Daily

• Cycling

• Light Cardio

• Yoga
""")

    # =====================
    # HEART
    # =====================

    elif disease == "Heart Disease":

        st.success("""
### ❤️ Treatment Recommendations

• Consult Cardiologist

• Monitor Blood Pressure

• Control Cholesterol

• Take Prescribed Medication

• Stop Smoking

• Reduce Stress
""")

        st.info("""
### 🥗 Diet Plan

• Oats

• Fruits

• Vegetables

• Fish

• Low Fat Foods

• Reduce Salt Intake
""")

        st.warning("""
### ⚠ Precautions

• Avoid Smoking

• Avoid Alcohol

• Monitor Heart Health

• Emergency Care if Chest Pain Occurs
""")

        st.success("""
### 🏃 Exercise Plan

• Walking

• Light Jogging

• Cardio Exercises

• Breathing Exercises
""")

    # =====================
    # KIDNEY
    # =====================

    else:

        st.success("""
### 🩺 Treatment Recommendations

• Consult Nephrologist

• Monitor Kidney Function

• Control Blood Pressure

• Maintain Hydration

• Regular Medical Checkups
""")

        st.info("""
### 🥗 Diet Plan

• Low Sodium Foods

• Fresh Vegetables

• Controlled Protein Intake

• Avoid Processed Foods

• Adequate Water Intake
""")

        st.warning("""
### ⚠ Precautions

• Avoid Excess Salt

• Avoid Self Medication

• Monitor Creatinine Levels

• Follow Doctor Advice
""")

        st.success("""
### 🏃 Exercise Plan

• Walking

• Stretching

• Yoga

• Light Physical Activity
""")

    # =====================
    # FOLLOW UP
    # =====================

    st.markdown("---")

    a, b, c = st.columns(3)

    with a:
        st.metric("Follow-up", "30 Days")

    with b:
        st.metric("Recovery Score", "92%")

    with c:
        st.metric("AI Confidence", "97%")

    # =====================
    # REPORT
    # =====================

    report = f"""
Treatment Recommendation Report

Disease: {disease}
Severity: {severity}

Generated by Healthcare AI Platform
"""

    st.download_button(
        "📄 Download Report",
        report,
        file_name="treatment_report.txt"
    )